### ISSUE TITLE
Don't spit out warning on missing entries

### ISSUE THREAD

**Issue by xSmurf** [subgraph/paxrat#10]
Paxrat spits out a warning if an executable listed in the config doesn't exist. It probably shouldn't spit out anything.

From: https://github.com/subgraph/subgraph-os-issues/issues/90

**Comment by mckinney-subgraph** [comment]
Fixed in: https://github.com/subgraph/paxrat/commit/ebde82d3e7892c94b4ecc5b5818a1de3d1d56f38

Will also clean up the general output soon.
