### ISSUE TITLE
/usr/bin/pulseaudio needs mprotect exception

### ISSUE THREAD

**Issue by dma** [subgraph/paxrat#14]
syslog:Oct 16 16:29:44 subgraph org.gnome.Shell.desktop[1328]: /usr/bin/pulseaudio: error 
                 while loading shared libraries: cannot make segment writable for relocation: Permission 
                 denied

**Comment by mckinney-subgraph** [comment]
Added: https://github.com/subgraph/paxrat/commit/c11dde743b23de0858e562dd4437f0b30689c0a3
