### ISSUE TITLE
Apply additional user-maintained conf file after apt changes

### ISSUE THREAD

**Issue by psivesely** [subgraph/paxrat#18]
Since `/etc/paxrat/paxrat.conf` is updated periodically by the Subgraph team, making sure to get your latest changes while keeping my custom flags requires frequent manual intervention. If it were possible have paxrat apply another file in addition after apt changes that would simplify my life and probably others'.

**Comment by xSmurf** [comment]
Hey @fowlslegs you can call `paxrat -c /path/to/config`.

You can similarly copy `/etc/apt/apt.conf.d/70paxrat` to another apt config file and add the other dpkg hook there:

```
DPkg::Post-Invoke { "/sbin/paxrat -x -c /etc/paxrat/paxrat-local.conf";}
```

I'll leave the ticket opened though as a reminder that we still want to implement independent system + user maintained configs at some point in the future.

**Comment by mckinney-subgraph** [comment]
Yes, also feel free to send us the flags you are missing and we can add them to `paxrat.conf`.

**Comment by mckinney-subgraph** [comment]
paxrat (when run with no args or the default config path) will now pick up PaX flag config files from `/etc/paxrat/conf.d`.
