### ISSUE TITLE
add pax rules for tahoe-lafs

### ISSUE THREAD

**Issue by david415** [subgraph/paxrat#19]
i run tahoe-lafs via python virtual env, so my paxrat rule looks like this:
```
  "/home/user/virtenv-tahoe/bin/python2": {
    "flags": "m",
    "nonroot": true
  },
```

**Comment by mckinney-subgraph** [comment]
This isn't really portable. `paxrat` now supports putting user configurations in `/etc/paxrat/conf.d/`, so the preferred solution is to drop this config there. We will be released a new `paxrat` package for Subgraph OS shortly that supports this.
