### ISSUE TITLE
Support for code comments in conf

### ISSUE THREAD

**Issue by HulaHoopWhonix** [subgraph/paxrat#2]
As the conf file is expanded to cover more programs there will be the problem of manageability. Emulating paxd's conf commenting scheme will be necessary to make the list more readable: https://github.com/thestinger/paxd/blob/master/paxd.conf

You can't use comments inside a JSON file by design.[1]

However you can play some tricks with JSmin so that the comments in the original file are removed before the code is handed to the parser.[2][3]

[1] https://stackoverflow.com/questions/244777/can-i-use-comments-inside-a-json-file
[2] https://www.quora.com/How-do-I-write-comments-inside-a-JSON-document
[3] http://www.crockford.com/javascript/jsmin.html

**Comment by mckinney-subgraph** [comment]
Hmm... I don't like the idea adding a jsmin as a dependency and then having it run every time paxrat is run, which can be quite often depending on how paxrat is triggered (for example, in a dpkg hook). It is added complexity, more (external) moving parts that can potentially cause dpkg to abort.

The conf file currently consists of flags + binary path + nonroot boolean. This is already pretty self-documenting IMHO. I do see a purpose in grouping flags categorically (which seems to be the main reason people want to comment their PaX flags) but I had intended to address this via a "paxrat.d/" arrangement where you could just create conf files for different categories such as "browsers.conf".

derlaft's patch for handling JSON comments does look interesting though, this would be a better solution than jsmin.

**Comment by mckinney-subgraph** [comment]
Closed by PR from @derlaft, thanks!
