### ISSUE TITLE
add /usr/bin/mono-sgen

### ISSUE THREAD

**Issue by kibal** [subgraph/paxrat#28]
This stanza is needed to build gtk golang packages on SubgraphOS:
```
  "/usr/bin/mono-sgen": {
    "flags": "m"
  },
```

**Comment by mckinney-subgraph** [comment]
This flag is already in `paxrat.conf`. Is it possible there was another `mono-*` related binary that was causing the problem? Closing the issue, feel free to re-open if another change is needed in relation to this.
