### ISSUE TITLE
Package licensing and metadata

### ISSUE THREAD

**Issue by HulaHoopWhonix** [subgraph/paxrat#4]
Please provide info like package license and the  author's name and email needed for inclusion in Debian.

**Comment by adrelanos** [comment]
Please provide info like package license and the author's name and email. Adding a license file to the repository. And a license/authorship file to all source files.

This is a pre-condition required before inclusion into official Debian repositories will be possible.

**Comment by mckinney-subgraph** [comment]
Closed by commit a342d951e11462c0986b51e8dc0d4dfc74b5d310.
