### ISSUE TITLE
Project whitelist scope

### ISSUE THREAD

**Issue by HulaHoopWhonix** [subgraph/paxrat#7]
The whitelist conf depends on the scope of programs Subgraph intends to cover. Is your project interested in a general list that covers as many Debian packages as possible? Or will you limit the exceptions to only cover the curated packages you allow?

If the latter then the conf.d approach is best so we avoid relying on messy solutions like config-package-dev displace. Can you please add .d support?

**Comment by mckinney-subgraph** [comment]
conf.d support added. We are interested in a general list to cover as many packages as possible.
